//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIIProject_travel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbJoutaEntities : DbContext
    {
        public dbJoutaEntities()
            : base("name=dbJoutaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tActivity> tActivity { get; set; }
        public virtual DbSet<tBlogComment> tBlogComment { get; set; }
        public virtual DbSet<tComment> tComment { get; set; }
        public virtual DbSet<tMember> tMember { get; set; }
    }
}
