//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIIProject_travel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tComment
    {
        public int fID { get; set; }
        public string f電子郵件 { get; set; }
        public string f電話 { get; set; }
        public string f標題 { get; set; }
        public string f意見 { get; set; }
        public string f性別 { get; set; }
        public string f聯絡人 { get; set; }
        public string f意見類型 { get; set; }
        public string f意見時間 { get; set; }
        public string f意見狀態 { get; set; }
    }
}
